# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dronjax's Blog
email: mail@dronjax.com
description: > # this means to ignore newlines until "baseurl:"
  Blogs of experiments, explorations and experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.dronjax.com" # the base hostname & protocol for your site
twitter_username: dronjax
github_username:  dronjax

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
